Repository Ragarnoy/Inception-of-Things, pull requests merged in 2022-11, with the labels that each got.

#14 Populate the vagrant-file to create 2 VM for the first part
  .editorconfig
  .gitignore
  P1/Vagrantfile
Labels: p1

#20 Configure k3s in controller mode on the main server vm
  .gitignore
  P1/Vagrantfile
Labels: p1

#21 Configure k3s agent node on server worker vm
  P1/Vagrantfile
Labels: p1

#26 Config vagrant for part 2
  .editorconfig
  .gitignore
  P2/README.md
  P2/Vagrantfile
Labels: p2

#32 Config 3 simple webapp
  P2/README.md
  P2/files/00-app1.yml
  P2/files/00-app2.yml
  P2/files/00-app3.yml
  P2/files/01-services.yml
  P2/files/02-ingress.yml
Labels: p2

#34 [P3] Config vagrant to create a vm that is ready for k3d
  P3/Vagrantfile
  P3/play_k3d.yml
Labels: p3

#43 update k3s script source to avoid unwanted updates
  P1/Vagrantfile
  P2/Vagrantfile
Labels: p1, p2
